### ISSUE TITLE
Todo: Towards numerical values

### ISSUE THREAD

**Issue by Lilia-Chen** [ChenYunyue/SAMME-Multi-class-AdaBoost-with-Sample-Weighted-Binary-Decision-Tree#1]
The decision tree needs to support numerical values:
1. Suppose only need to deal with numerical values;
2. Find the best threshold for dichotomy by traversing all attribute values in the dataset

**Comment by Lilia-Chen** [comment]
14th June:
1. Changed class for tree node;
2. split the data by the threshold.

**Comment by ChenYunyue** [comment]
16th June:
Finish.

**Comment by Lilia-Chen** [comment]
16th June
Now it can deal with numerical values.
