### ISSUE TITLE
Todo: Decision tree class encapsulation

### ISSUE THREAD

**Issue by Lilia-Chen** [ChenYunyue/SAMME-Multi-class-AdaBoost-with-Sample-Weighted-Binary-Decision-Tree#2]
The decision tree algorithm cannot just be a few functions. Define a class!

**Comment by ChenYunyue** [comment]
14th June:
1. Changed class for tree node;
2. split the data by the threshold.

**Comment by Lilia-Chen** [comment]
16th
Finish MyDecisionTreeClassifier.
